// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2aT8_lvf-zuQBZTGCsUlyxYaPgiQjADk',
    appId: '1:156496435015:web:2356bb6e933a851b871e62',
    messagingSenderId: '156496435015',
    projectId: 'supbike-9475f',
    authDomain: 'supbike-9475f.firebaseapp.com',
    storageBucket: 'supbike-9475f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtPtscoTuwA_rzZfXfPW7LKZTV4AoHZt0',
    appId: '1:156496435015:android:31cbc1934d9191ff871e62',
    messagingSenderId: '156496435015',
    projectId: 'supbike-9475f',
    storageBucket: 'supbike-9475f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbGbNKCczf-KBesa-J22t1qVOazVUiCNU',
    appId: '1:156496435015:ios:6e469607c19c5e19871e62',
    messagingSenderId: '156496435015',
    projectId: 'supbike-9475f',
    storageBucket: 'supbike-9475f.appspot.com',
    iosBundleId: 'com.example.supbike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbGbNKCczf-KBesa-J22t1qVOazVUiCNU',
    appId: '1:156496435015:ios:1002da20cbf97334871e62',
    messagingSenderId: '156496435015',
    projectId: 'supbike-9475f',
    storageBucket: 'supbike-9475f.appspot.com',
    iosBundleId: 'com.example.supbike.RunnerTests',
  );
}
